Site local Alchimie: AlchimieBAJ\main\pdf\PDF Class Reference
AlchimieBAJ\main\pdf\PDF Class Reference
Public Member Functions
Header ()
Footer ()
EcrireSurPlusieursLignes ($entree, $taille, $nb_lignes)
NbLines ($w, $txt)
Table ($col_titles, $col_widths, $table_content, $titre='', $decalage=10)
Public Member Functions inherited from FPDF
__construct ($orientation='P', $unit='mm', $size='A4')
SetMargins ($left, $top, $right=null)
SetLeftMargin ($margin)
SetTopMargin ($margin)
SetRightMargin ($margin)
SetAutoPageBreak ($auto, $margin=0)
SetDisplayMode ($zoom, $layout='default')
SetCompression ($compress)
SetTitle ($title, $isUTF8=false)
SetAuthor ($author, $isUTF8=false)
SetSubject ($subject, $isUTF8=false)
SetKeywords ($keywords, $isUTF8=false)
SetCreator ($creator, $isUTF8=false)
AliasNbPages ($alias='{nb}')
Error ($msg)
Close ()
AddPage ($orientation='', $size='', $rotation=0)
PageNo ()
SetDrawColor ($r, $g=null, $b=null)
SetFillColor ($r, $g=null, $b=null)
SetTextColor ($r, $g=null, $b=null)
GetStringWidth ($s)
SetLineWidth ($width)
Line ($x1, $y1, $x2, $y2)
Rect ($x, $y, $w, $h, $style='')
AddFont ($family, $style='', $file='', $dir='')
SetFont ($family, $style='', $size=0)
SetFontSize ($size)
AddLink ()
SetLink ($link, $y=0, $page=-1)
Link ($x, $y, $w, $h, $link)
Text ($x, $y, $txt)
AcceptPageBreak ()
Cell ($w, $h=0, $txt='', $border=0, $ln=0, $align='', $fill=false, $link='')
MultiCell ($w, $h, $txt, $border=0, $align='J', $fill=false)
Write ($h, $txt, $link='')
Ln ($h=null)
Image ($file, $x=null, $y=null, $w=0, $h=0, $type='', $link='')
GetPageWidth ()
GetPageHeight ()
GetX ()
SetX ($x)
GetY ()
SetY ($y, $resetX=true)
SetXY ($x, $y)
Output ($dest='', $name='', $isUTF8=false)
Public Attributes
$title = ''
Public Attributes inherited from FPDF
const VERSION = '1.86'
$hPt
$h
$y
Additional Inherited Members
Protected Member Functions inherited from FPDF
_checkoutput ()
_getpagesize ($size)
_beginpage ($orientation, $size, $rotation)
_endpage ()
_loadfont ($path)
_isascii ($s)
_httpencode ($param, $value, $isUTF8)
_UTF8encode ($s)
_UTF8toUTF16 ($s)
_escape ($s)
_textstring ($s)
_dounderline ($x, $y, $txt)
_parsejpg ($file)
_parsepng ($file)
_parsepngstream ($f, $file)
_readstream ($f, $n)
_readint ($f)
_parsegif ($file)
_out ($s)
_put ($s)
_getoffset ()
_newobj ($n=null)
_putstream ($data)
_putstreamobject ($data)
_putlinks ($n)
_putpage ($n)
_putpages ()
_putfonts ()
_tounicodecmap ($uv)
_putimages ()
_putimage (&$info)
_putxobjectdict ()
_putresourcedict ()
_putresources ()
_putinfo ()
_putcatalog ()
_putheader ()
_puttrailer ()
_enddoc ()
Protected Attributes inherited from FPDF
$page
$n
$offsets
$buffer
$pages
$state
$compress
$iconv
$k
$DefOrientation
$CurOrientation
$StdPageSizes
$DefPageSize
$CurPageSize
$CurRotation
$PageInfo
$wPt
$w
$lMargin
$tMargin
$rMargin
$bMargin
$cMargin
$x
$lasth
$LineWidth
$fontpath
$CoreFonts
$fonts
$FontFiles
$encodings
$cmaps
$FontFamily
$FontStyle
$underline
$CurrentFont
$FontSizePt
$FontSize
$DrawColor
$FillColor
$TextColor
$ColorFlag
$WithAlpha
$ws
$images
$PageLinks
$links
$AutoPageBreak
$PageBreakTrigger
$InHeader
$InFooter
$AliasNbPages
$ZoomMode
$LayoutMode
$metadata
$CreationDate
$PDFVersion
Detailed Description
Definition at line 8 of file PDF.php.
Member Function Documentation
EcrireSurPlusieursLignes()
AlchimieBAJ\main\pdf\PDF::EcrireSurPlusieursLignes ($entree, $taille, $nb_lignes)
Divise une entrée en plusieurs lignes si sa largeur dépasse la taille donnée.
Parameters
string $entree L'entrée à diviser en lignes.
integer $taille La taille maximale des lignes.
integer $nb_lignes Le nombre de lignes avant l'écriture.
Returns
int Le nombre de lignes après l'écriture.
Definition at line 65 of file PDF.php.
References FPDF\Cell(), and FPDF\GetStringWidth().
Footer()
AlchimieBAJ\main\pdf\PDF::Footer ()
Reimplemented from FPDF.
Definition at line 44 of file PDF.php.
References FPDF\Cell(), FPDF\PageNo(), FPDF\SetFont(), and FPDF\SetY().
Header()
AlchimieBAJ\main\pdf\PDF::Header ()
Reimplemented from FPDF.
Definition at line 12 of file PDF.php.
References FPDF\$w, FPDF\AddFont(), FPDF\Cell(), FPDF\GetStringWidth(), FPDF\Image(), FPDF\Ln(), FPDF\PageNo(), FPDF\SetFont(), FPDF\SetTextColor(), and FPDF\SetX().
NbLines()
AlchimieBAJ\main\pdf\PDF::NbLines ($w, $txt)
Calcule le nombre de lignes nécessaires pour afficher un texte donné dans une cellule.
Parameters
float $w La largeur de la cellule.
string $txt Le texte à afficher dans la cellule.
Returns
int Le nombre de lignes nécessaires pour afficher le texte.
Definition at line 104 of file PDF.php.
References FPDF\$w, and FPDF\GetStringWidth().
Referenced by AlchimieBAJ\main\pdf\PDF\Table().
Table()
AlchimieBAJ\main\pdf\PDF::Table ($col_titles, $col_widths, $table_content, $titre = '', $decalage = 10)
Crée un tableau avec des en-têtes de colonnes personnalisés et des données pour chaque ligne. Les couleurs et la police sont définies pour chaque élément du tableau.
Parameters
array $col_titles un tableau contenant les en-têtes pour chaque colonne du tableau
array $col_widths un tableau contenant les largeurs de colonne pour chaque colonne
array $table_content un tableau multidimensionnel contenant les données à afficher dans le tableau
string $titre une chaine de caractères correspondant au titre à mettre sur le tableau (facultatif, par défaut '')
int $decalage un décalage optionnel pour aligner le tableau différemment (facultatif, par défaut 10)
Returns
void
Definition at line 144 of file PDF.php.
References FPDF\AddPage(), FPDF\Cell(), FPDF\GetPageHeight(), FPDF\GetX(), FPDF\GetY(), FPDF\Ln(), FPDF\MultiCell(), AlchimieBAJ\main\pdf\PDF\NbLines(), FPDF\SetFillColor(), FPDF\SetFont(), FPDF\SetTextColor(), FPDF\SetX(), and FPDF\SetXY().
Member Data Documentation
$title
AlchimieBAJ\main\pdf\PDF::$title = ''
Definition at line 10 of file PDF.php.
The documentation for this class was generated from the following file:
main/pdf/PDF.php