Site local Alchimie: FPDF Class Reference
FPDF Class Reference
Public Member Functions
__construct ($orientation='P', $unit='mm', $size='A4')
SetMargins ($left, $top, $right=null)
SetLeftMargin ($margin)
SetTopMargin ($margin)
SetRightMargin ($margin)
SetAutoPageBreak ($auto, $margin=0)
SetDisplayMode ($zoom, $layout='default')
SetCompression ($compress)
SetTitle ($title, $isUTF8=false)
SetAuthor ($author, $isUTF8=false)
SetSubject ($subject, $isUTF8=false)
SetKeywords ($keywords, $isUTF8=false)
SetCreator ($creator, $isUTF8=false)
AliasNbPages ($alias='{nb}')
Error ($msg)
Close ()
AddPage ($orientation='', $size='', $rotation=0)
Header ()
Footer ()
PageNo ()
SetDrawColor ($r, $g=null, $b=null)
SetFillColor ($r, $g=null, $b=null)
SetTextColor ($r, $g=null, $b=null)
GetStringWidth ($s)
SetLineWidth ($width)
Line ($x1, $y1, $x2, $y2)
Rect ($x, $y, $w, $h, $style='')
AddFont ($family, $style='', $file='', $dir='')
SetFont ($family, $style='', $size=0)
SetFontSize ($size)
AddLink ()
SetLink ($link, $y=0, $page=-1)
Link ($x, $y, $w, $h, $link)
Text ($x, $y, $txt)
AcceptPageBreak ()
Cell ($w, $h=0, $txt='', $border=0, $ln=0, $align='', $fill=false, $link='')
MultiCell ($w, $h, $txt, $border=0, $align='J', $fill=false)
Write ($h, $txt, $link='')
Ln ($h=null)
Image ($file, $x=null, $y=null, $w=0, $h=0, $type='', $link='')
GetPageWidth ()
GetPageHeight ()
GetX ()
SetX ($x)
GetY ()
SetY ($y, $resetX=true)
SetXY ($x, $y)
Output ($dest='', $name='', $isUTF8=false)
Public Attributes
const VERSION = '1.86'
$hPt
$h
$y
Protected Member Functions
_checkoutput ()
_getpagesize ($size)
_beginpage ($orientation, $size, $rotation)
_endpage ()
_loadfont ($path)
_isascii ($s)
_httpencode ($param, $value, $isUTF8)
_UTF8encode ($s)
_UTF8toUTF16 ($s)
_escape ($s)
_textstring ($s)
_dounderline ($x, $y, $txt)
_parsejpg ($file)
_parsepng ($file)
_parsepngstream ($f, $file)
_readstream ($f, $n)
_readint ($f)
_parsegif ($file)
_out ($s)
_put ($s)
_getoffset ()
_newobj ($n=null)
_putstream ($data)
_putstreamobject ($data)
_putlinks ($n)
_putpage ($n)
_putpages ()
_putfonts ()
_tounicodecmap ($uv)
_putimages ()
_putimage (&$info)
_putxobjectdict ()
_putresourcedict ()
_putresources ()
_putinfo ()
_putcatalog ()
_putheader ()
_puttrailer ()
_enddoc ()
Protected Attributes
$page
$n
$offsets
$buffer
$pages
$state
$compress
$iconv
$k
$DefOrientation
$CurOrientation
$StdPageSizes
$DefPageSize
$CurPageSize
$CurRotation
$PageInfo
$wPt
$w
$lMargin
$tMargin
$rMargin
$bMargin
$cMargin
$x
$lasth
$LineWidth
$fontpath
$CoreFonts
$fonts
$FontFiles
$encodings
$cmaps
$FontFamily
$FontStyle
$underline
$CurrentFont
$FontSizePt
$FontSize
$DrawColor
$FillColor
$TextColor
$ColorFlag
$WithAlpha
$ws
$images
$PageLinks
$links
$AutoPageBreak
$PageBreakTrigger
$InHeader
$InFooter
$AliasNbPages
$ZoomMode
$LayoutMode
$metadata
$CreationDate
$PDFVersion
Detailed Description
Definition at line 10 of file fpdf.php.
Constructor & Destructor Documentation
__construct()
FPDF::__construct ($orientation = 'P', $unit = 'mm', $size = 'A4')
Definition at line 75 of file fpdf.php.
References $DefOrientation, $k, _getpagesize(), Error(), SetAutoPageBreak(), SetCompression(), SetDisplayMode(), and SetMargins().
Member Function Documentation
_beginpage()
FPDF::_beginpage ($orientation, $size, $rotation) protected
Definition at line 1081 of file fpdf.php.
References $bMargin, $DefOrientation, $DefPageSize, $k, $lMargin, $page, $tMargin, _getpagesize(), and Error().
Referenced by AddPage().
_checkoutput()
FPDF::_checkoutput () protected
Definition at line 1042 of file fpdf.php.
References $file, and Error().
Referenced by Output().
_dounderline()
FPDF::_dounderline ($x, $y, $txt) protected
Definition at line 1243 of file fpdf.php.
References $up, $ut, $w, $x, $y, and GetStringWidth().
_enddoc()
FPDF::_enddoc () protected
Definition at line 1898 of file fpdf.php.
Referenced by Close().
_endpage()
FPDF::_endpage () protected
Definition at line 1129 of file fpdf.php.
Referenced by AddPage(), and Close().
_escape()
FPDF::_escape ($s) protected
Definition at line 1226 of file fpdf.php.
Referenced by Cell(), and Text().
_getoffset()
FPDF::_getoffset () protected
Definition at line 1476 of file fpdf.php.
_getpagesize()
FPDF::_getpagesize ($size) protected
Definition at line 1062 of file fpdf.php.
References Error().
Referenced by __construct(), and _beginpage().
_httpencode()
FPDF::_httpencode ($param, $value, $isUTF8) protected
Definition at line 1159 of file fpdf.php.
References AlchimieBAJ\main\ajax\$param, _isascii(), and _UTF8encode().
Referenced by Output().
_isascii()
FPDF::_isascii ($s) protected
Definition at line 1147 of file fpdf.php.
Referenced by _httpencode(), and _textstring().
_loadfont()
FPDF::_loadfont ($path) protected
Definition at line 1134 of file fpdf.php.
References $enc, $name, $subsetted, and Error().
Referenced by AddFont().
_newobj()
FPDF::_newobj ($n = null) protected
Definition at line 1481 of file fpdf.php.
_out()
FPDF::_out ($s) protected
Definition at line 1457 of file fpdf.php.
Referenced by AddPage(), Cell(), Image(), Line(), MultiCell(), Rect(), SetDrawColor(), SetFillColor(), SetFont(), SetFontSize(), SetLineWidth(), and Text().
_parsegif()
FPDF::_parsegif ($file) protected
Definition at line 1432 of file fpdf.php.
References AlchimieBAJ\main\ajax\$data, and $file.
_parsejpg()
FPDF::_parsejpg ($file) protected
Definition at line 1252 of file fpdf.php.
References AlchimieBAJ\main\ajax\$data, $file, and Error().
_parsepng()
FPDF::_parsepng ($file) protected
Definition at line 1271 of file fpdf.php.
References $file, _parsepngstream(), and Error().
_parsepngstream()
FPDF::_parsepngstream ($f, $file) protected
Definition at line 1282 of file fpdf.php.
References AlchimieBAJ\main\ajax\$data, $file, $h, $n, AlchimieBAJ\main\ajax\$type, $w, _readint(), _readstream(), and Error().
Referenced by _parsepng().
_put()
FPDF::_put ($s) protected
Definition at line 1470 of file fpdf.php.
_putcatalog()
FPDF::_putcatalog () protected
Definition at line 1865 of file fpdf.php.
_putfonts()
FPDF::_putfonts () protected
Definition at line 1604 of file fpdf.php.
References $cw, $file, $name, and AlchimieBAJ\main\ajax\$type.
_putheader()
FPDF::_putheader () protected
Definition at line 1886 of file fpdf.php.
_putimage()
FPDF::_putimage (& $info) protected
Definition at line 1782 of file fpdf.php.
_putimages()
FPDF::_putimages () protected
Definition at line 1772 of file fpdf.php.
References $file.
_putinfo()
FPDF::_putinfo () protected
Definition at line 1857 of file fpdf.php.
_putlinks()
FPDF::_putlinks ($n) protected
Definition at line 1513 of file fpdf.php.
_putpage()
FPDF::_putpage ($n) protected
Definition at line 1536 of file fpdf.php.
_putpages()
FPDF::_putpages () protected
Definition at line 1566 of file fpdf.php.
_putresourcedict()
FPDF::_putresourcedict () protected
Definition at line 1833 of file fpdf.php.
_putresources()
FPDF::_putresources () protected
Definition at line 1845 of file fpdf.php.
_putstream()
FPDF::_putstream ($data) protected
Definition at line 1490 of file fpdf.php.
References AlchimieBAJ\main\ajax\$data.
_putstreamobject()
FPDF::_putstreamobject ($data) protected
Definition at line 1497 of file fpdf.php.
References AlchimieBAJ\main\ajax\$data.
_puttrailer()
FPDF::_puttrailer () protected
Definition at line 1891 of file fpdf.php.
_putxobjectdict()
FPDF::_putxobjectdict () protected
Definition at line 1827 of file fpdf.php.
_readint()
FPDF::_readint ($f) protected
Definition at line 1425 of file fpdf.php.
Referenced by _parsepngstream().
_readstream()
FPDF::_readstream ($f, $n) protected
Definition at line 1408 of file fpdf.php.
References AlchimieBAJ\main\ajax\$res.
Referenced by _parsepngstream().
_textstring()
FPDF::_textstring ($s) protected
Definition at line 1235 of file fpdf.php.
References _isascii(), and _UTF8toUTF16().
_tounicodecmap()
FPDF::_tounicodecmap ($uv) protected
Definition at line 1721 of file fpdf.php.
References $uv.
_UTF8encode()
FPDF::_UTF8encode ($s) protected
Definition at line 1169 of file fpdf.php.
References AlchimieBAJ\main\ajax\$res.
Referenced by _httpencode(), SetAuthor(), SetCreator(), SetKeywords(), SetSubject(), and SetTitle().
_UTF8toUTF16()
FPDF::_UTF8toUTF16 ($s) protected
Definition at line 1191 of file fpdf.php.
References AlchimieBAJ\main\ajax\$res.
Referenced by _textstring().
AcceptPageBreak()
FPDF::AcceptPageBreak ()
Definition at line 574 of file fpdf.php.
References $AutoPageBreak.
Referenced by Cell(), and Image().
AddFont()
FPDF::AddFont ($family, $style = '', $file = '', $dir = '')
Definition at line 443 of file fpdf.php.
References $file, $fontpath, _loadfont(), and Error().
Referenced by AlchimieBAJ\main\pdf\PDF\Header(), and SetFont().
AddLink()
FPDF::AddLink ()
Definition at line 536 of file fpdf.php.
References $n.
AddPage()
FPDF::AddPage ($orientation = '', $size = '', $rotation = 0)
Definition at line 287 of file fpdf.php.
References $ColorFlag, $DrawColor, $FillColor, $FontFamily, $FontSizePt, $LineWidth, $TextColor, _beginpage(), _endpage(), _out(), Error(), Footer(), Header(), and SetFont().
Referenced by Cell(), Close(), Image(), and AlchimieBAJ\main\pdf\PDF\Table().
AliasNbPages()
FPDF::AliasNbPages ($alias = '{nb}')
Definition at line 258 of file fpdf.php.
Cell()
FPDF::Cell ($w, $h = 0, $txt = '', $border = 0, $ln = 0, $align = '', $fill = false, $link = '')
Definition at line 580 of file fpdf.php.
References $cMargin, $h, $k, $lMargin, $w, $ws, $x, $y, _escape(), _out(), AcceptPageBreak(), AddPage(), Error(), GetStringWidth(), and Link().
Referenced by AlchimieBAJ\main\pdf\PDF\EcrireSurPlusieursLignes(), AlchimieBAJ\main\pdf\PDF\Footer(), AlchimieBAJ\main\pdf\PDF\Header(), MultiCell(), AlchimieBAJ\main\pdf\PDF\Table(), and Write().
Close()
FPDF::Close ()
Definition at line 270 of file fpdf.php.
References _enddoc(), _endpage(), AddPage(), and Footer().
Referenced by Output().
Error()
FPDF::Error ($msg)
Definition at line 264 of file fpdf.php.
Referenced by __construct(), _beginpage(), _checkoutput(), _getpagesize(), _loadfont(), _parsejpg(), _parsepng(), _parsepngstream(), AddFont(), AddPage(), Cell(), Image(), MultiCell(), Output(), SetDisplayMode(), SetFont(), Text(), and Write().
Footer()
FPDF::Footer ()
Reimplemented in AlchimieBAJ\main\pdf\PDF.
Definition at line 361 of file fpdf.php.
Referenced by AddPage(), and Close().
GetPageHeight()
FPDF::GetPageHeight ()
Definition at line 940 of file fpdf.php.
References $h.
Referenced by AlchimieBAJ\main\pdf\PDF\Table().
GetPageWidth()
FPDF::GetPageWidth ()
Definition at line 934 of file fpdf.php.
References $w.
GetStringWidth()
FPDF::GetStringWidth ($s)
Definition at line 405 of file fpdf.php.
References $cw, and $w.
Referenced by _dounderline(), Cell(), AlchimieBAJ\main\pdf\PDF\EcrireSurPlusieursLignes(), AlchimieBAJ\main\pdf\PDF\Header(), and AlchimieBAJ\main\pdf\PDF\NbLines().
GetX()
FPDF::GetX ()
Definition at line 946 of file fpdf.php.
References $x.
Referenced by AlchimieBAJ\main\pdf\PDF\Table().
GetY()
FPDF::GetY ()
Definition at line 961 of file fpdf.php.
References $y.
Referenced by AlchimieBAJ\main\pdf\PDF\Table().
Header()
FPDF::Header ()
Reimplemented in AlchimieBAJ\main\pdf\PDF.
Definition at line 356 of file fpdf.php.
Referenced by AddPage().
Image()
FPDF::Image ($file, $x = null, $y = null, $w = 0, $h = 0, $type = '', $link = '')
Definition at line 869 of file fpdf.php.
References $file, $h, $k, AlchimieBAJ\main\ajax\$type, $w, $x, $y, _out(), AcceptPageBreak(), AddPage(), Error(), and Link().
Referenced by AlchimieBAJ\main\pdf\PDF\Header().
Line()
FPDF::Line ($x1, $y1, $x2, $y2)
Definition at line 425 of file fpdf.php.
References _out().
Link()
FPDF::Link ($x, $y, $w, $h, $link)
Definition at line 554 of file fpdf.php.
References $h, $page, $w, $x, and $y.
Referenced by Cell(), and Image().
Ln()
FPDF::Ln ($h = null)
Definition at line 859 of file fpdf.php.
References $h, $lasth, and $lMargin.
Referenced by AlchimieBAJ\main\pdf\PDF\Header(), and AlchimieBAJ\main\pdf\PDF\Table().
MultiCell()
FPDF::MultiCell ($w, $h, $txt, $border = 0, $align = 'J', $fill = false)
Definition at line 661 of file fpdf.php.
References $cMargin, $cw, $lMargin, $w, $x, _out(), Cell(), and Error().
Referenced by AlchimieBAJ\main\pdf\PDF\Table().
Output()
FPDF::Output ($dest = '', $name = '', $isUTF8 = false)
Definition at line 985 of file fpdf.php.
References $buffer, $name, _checkoutput(), _httpencode(), Close(), and Error().
PageNo()
FPDF::PageNo ()
Definition at line 366 of file fpdf.php.
References $page.
Referenced by AlchimieBAJ\main\pdf\PDF\Footer(), and AlchimieBAJ\main\pdf\PDF\Header().
Rect()
FPDF::Rect ($x, $y, $w, $h, $style = '')
Definition at line 431 of file fpdf.php.
References $h, $w, $x, $y, and _out().
SetAuthor()
FPDF::SetAuthor ($author, $isUTF8 = false)
Definition at line 234 of file fpdf.php.
References _UTF8encode().
SetAutoPageBreak()
FPDF::SetAutoPageBreak ($auto, $margin = 0)
Definition at line 198 of file fpdf.php.
Referenced by __construct().
SetCompression()
FPDF::SetCompression ($compress)
Definition at line 219 of file fpdf.php.
References $compress.
Referenced by __construct().
SetCreator()
FPDF::SetCreator ($creator, $isUTF8 = false)
Definition at line 252 of file fpdf.php.
References _UTF8encode().
SetDisplayMode()
FPDF::SetDisplayMode ($zoom, $layout = 'default')
Definition at line 206 of file fpdf.php.
References Error().
Referenced by __construct().
SetDrawColor()
FPDF::SetDrawColor ($r, $g = null, $b = null)
Definition at line 372 of file fpdf.php.
References _out().
SetFillColor()
FPDF::SetFillColor ($r, $g = null, $b = null)
Definition at line 383 of file fpdf.php.
References $TextColor, and _out().
Referenced by AlchimieBAJ\main\pdf\PDF\Table().
SetFont()
FPDF::SetFont ($family, $style = '', $size = 0)
Definition at line 475 of file fpdf.php.
References $FontFamily, $FontSizePt, $k, _out(), AddFont(), and Error().
Referenced by AddPage(), AlchimieBAJ\main\pdf\PDF\Footer(), AlchimieBAJ\main\pdf\PDF\Header(), and AlchimieBAJ\main\pdf\PDF\Table().
SetFontSize()
FPDF::SetFontSize ($size)
Definition at line 525 of file fpdf.php.
References $k, and _out().
SetKeywords()
FPDF::SetKeywords ($keywords, $isUTF8 = false)
Definition at line 246 of file fpdf.php.
References _UTF8encode().
SetLeftMargin()
FPDF::SetLeftMargin ($margin)
Definition at line 178 of file fpdf.php.
SetLineWidth()
FPDF::SetLineWidth ($width)
Definition at line 417 of file fpdf.php.
References _out().
SetLink()
FPDF::SetLink ($link, $y = 0, $page = -1)
Definition at line 544 of file fpdf.php.
References $page, and $y.
SetMargins()
FPDF::SetMargins ($left, $top, $right = null)
Definition at line 168 of file fpdf.php.
Referenced by __construct().
SetRightMargin()
FPDF::SetRightMargin ($margin)
Definition at line 192 of file fpdf.php.
SetSubject()
FPDF::SetSubject ($subject, $isUTF8 = false)
Definition at line 240 of file fpdf.php.
References _UTF8encode().
SetTextColor()
FPDF::SetTextColor ($r, $g = null, $b = null)
Definition at line 395 of file fpdf.php.
References $TextColor.
Referenced by AlchimieBAJ\main\pdf\PDF\Header(), and AlchimieBAJ\main\pdf\PDF\Table().
SetTitle()
FPDF::SetTitle ($title, $isUTF8 = false)
Definition at line 228 of file fpdf.php.
References _UTF8encode().
SetTopMargin()
FPDF::SetTopMargin ($margin)
Definition at line 186 of file fpdf.php.
SetX()
FPDF::SetX ($x)
Definition at line 952 of file fpdf.php.
References $x.
Referenced by AlchimieBAJ\main\pdf\PDF\Header(), SetXY(), and AlchimieBAJ\main\pdf\PDF\Table().
SetXY()
FPDF::SetXY ($x, $y)
Definition at line 978 of file fpdf.php.
References $x, SetX(), and SetY().
Referenced by AlchimieBAJ\main\pdf\PDF\Table().
SetY()
FPDF::SetY ($y, $resetX = true)
Definition at line 967 of file fpdf.php.
References $lMargin, and $y.
Referenced by AlchimieBAJ\main\pdf\PDF\Footer(), and SetXY().
Text()
FPDF::Text ($x, $y, $txt)
Definition at line 560 of file fpdf.php.
References $x, $y, _escape(), _out(), and Error().
Write()
FPDF::Write ($h, $txt, $link = '')
Definition at line 776 of file fpdf.php.
References $cMargin, $cw, $h, $lMargin, $w, $x, Cell(), and Error().
Member Data Documentation
$AliasNbPages
FPDF::$AliasNbPages protected
Definition at line 64 of file fpdf.php.
$AutoPageBreak
FPDF::$AutoPageBreak protected
Definition at line 60 of file fpdf.php.
Referenced by AcceptPageBreak().
$bMargin
FPDF::$bMargin protected
Definition at line 34 of file fpdf.php.
Referenced by _beginpage().
$buffer
FPDF::$buffer protected
Definition at line 16 of file fpdf.php.
Referenced by Output().
$cmaps
FPDF::$cmaps protected
Definition at line 44 of file fpdf.php.
$cMargin
FPDF::$cMargin protected
Definition at line 35 of file fpdf.php.
Referenced by Cell(), MultiCell(), and Write().
$ColorFlag
FPDF::$ColorFlag protected
Definition at line 54 of file fpdf.php.
Referenced by AddPage().
$compress
FPDF::$compress protected
Definition at line 19 of file fpdf.php.
Referenced by SetCompression().
$CoreFonts
FPDF::$CoreFonts protected
Definition at line 40 of file fpdf.php.
$CreationDate
FPDF::$CreationDate protected
Definition at line 68 of file fpdf.php.
$CurOrientation
FPDF::$CurOrientation protected
Definition at line 23 of file fpdf.php.
$CurPageSize
FPDF::$CurPageSize protected
Definition at line 26 of file fpdf.php.
$CurrentFont
FPDF::$CurrentFont protected
Definition at line 48 of file fpdf.php.
$CurRotation
FPDF::$CurRotation protected
Definition at line 27 of file fpdf.php.
$DefOrientation
FPDF::$DefOrientation protected
Definition at line 22 of file fpdf.php.
Referenced by __construct(), and _beginpage().
$DefPageSize
FPDF::$DefPageSize protected
Definition at line 25 of file fpdf.php.
Referenced by _beginpage().
$DrawColor
FPDF::$DrawColor protected
Definition at line 51 of file fpdf.php.
Referenced by AddPage().
$encodings
FPDF::$encodings protected
Definition at line 43 of file fpdf.php.
$FillColor
FPDF::$FillColor protected
Definition at line 52 of file fpdf.php.
Referenced by AddPage().
$FontFamily
FPDF::$FontFamily protected
Definition at line 45 of file fpdf.php.
Referenced by AddPage(), and SetFont().
$FontFiles
FPDF::$FontFiles protected
Definition at line 42 of file fpdf.php.
$fontpath
FPDF::$fontpath protected
Definition at line 39 of file fpdf.php.
Referenced by AddFont().
$fonts
FPDF::$fonts protected
Definition at line 41 of file fpdf.php.
$FontSize
FPDF::$FontSize protected
Definition at line 50 of file fpdf.php.
$FontSizePt
FPDF::$FontSizePt protected
Definition at line 49 of file fpdf.php.
Referenced by AddPage(), and SetFont().
$FontStyle
FPDF::$FontStyle protected
Definition at line 46 of file fpdf.php.
$h
FPDF::$h
Definition at line 30 of file fpdf.php.
Referenced by _parsepngstream(), Cell(), GetPageHeight(), Image(), Link(), Ln(), Rect(), and Write().
$hPt
FPDF::$hPt
Definition at line 29 of file fpdf.php.
$iconv
FPDF::$iconv protected
Definition at line 20 of file fpdf.php.
$images
FPDF::$images protected
Definition at line 57 of file fpdf.php.
$InFooter
FPDF::$InFooter protected
Definition at line 63 of file fpdf.php.
$InHeader
FPDF::$InHeader protected
Definition at line 62 of file fpdf.php.
$k
FPDF::$k protected
Definition at line 21 of file fpdf.php.
Referenced by __construct(), _beginpage(), Cell(), Image(), SetFont(), and SetFontSize().
$lasth
FPDF::$lasth protected
Definition at line 37 of file fpdf.php.
Referenced by Ln().
$LayoutMode
FPDF::$LayoutMode protected
Definition at line 66 of file fpdf.php.
$LineWidth
FPDF::$LineWidth protected
Definition at line 38 of file fpdf.php.
Referenced by AddPage().
$links
FPDF::$links protected
Definition at line 59 of file fpdf.php.
$lMargin
FPDF::$lMargin protected
Definition at line 31 of file fpdf.php.
Referenced by _beginpage(), Cell(), Ln(), MultiCell(), SetY(), and Write().
$metadata
FPDF::$metadata protected
Definition at line 67 of file fpdf.php.
$n
FPDF::$n protected
Definition at line 14 of file fpdf.php.
Referenced by _parsepngstream(), and AddLink().
$offsets
FPDF::$offsets protected
Definition at line 15 of file fpdf.php.
$page
FPDF::$page protected
Definition at line 13 of file fpdf.php.
Referenced by _beginpage(), Link(), PageNo(), and SetLink().
$PageBreakTrigger
FPDF::$PageBreakTrigger protected
Definition at line 61 of file fpdf.php.
$PageInfo
FPDF::$PageInfo protected
Definition at line 28 of file fpdf.php.
$PageLinks
FPDF::$PageLinks protected
Definition at line 58 of file fpdf.php.
$pages
FPDF::$pages protected
Definition at line 17 of file fpdf.php.
$PDFVersion
FPDF::$PDFVersion protected
Definition at line 69 of file fpdf.php.
$rMargin
FPDF::$rMargin protected
Definition at line 33 of file fpdf.php.
$state
FPDF::$state protected
Definition at line 18 of file fpdf.php.
$StdPageSizes
FPDF::$StdPageSizes protected
Definition at line 24 of file fpdf.php.
$TextColor
FPDF::$TextColor protected
Definition at line 53 of file fpdf.php.
Referenced by AddPage(), SetFillColor(), and SetTextColor().
$tMargin
FPDF::$tMargin protected
Definition at line 32 of file fpdf.php.
Referenced by _beginpage().
$underline
FPDF::$underline protected
Definition at line 47 of file fpdf.php.
$w
FPDF::$w protected
Definition at line 30 of file fpdf.php.
Referenced by _dounderline(), _parsepngstream(), Cell(), GetPageWidth(), GetStringWidth(), AlchimieBAJ\main\pdf\PDF\Header(), Image(), Link(), MultiCell(), AlchimieBAJ\main\pdf\PDF\NbLines(), Rect(), and Write().
$WithAlpha
FPDF::$WithAlpha protected
Definition at line 55 of file fpdf.php.
$wPt
FPDF::$wPt protected
Definition at line 29 of file fpdf.php.
$ws
FPDF::$ws protected
Definition at line 56 of file fpdf.php.
Referenced by Cell().
$x
FPDF::$x protected
Definition at line 36 of file fpdf.php.
Referenced by _dounderline(), Cell(), GetX(), Image(), Link(), MultiCell(), Rect(), SetX(), SetXY(), Text(), and Write().
$y
FPDF::$y
Definition at line 36 of file fpdf.php.
Referenced by _dounderline(), Cell(), GetY(), Image(), Link(), Rect(), SetLink(), SetY(), and Text().
$ZoomMode
FPDF::$ZoomMode protected
Definition at line 65 of file fpdf.php.
VERSION
const FPDF::VERSION = '1.86'
Definition at line 12 of file fpdf.php.
The documentation for this class was generated from the following file:
main/pdf/fpdf/fpdf.php