Site local Alchimie: main/pdf/fpdf/font/makefont/makefont.php File Reference
makefont.php File Reference
Functions
ReadMap ($enc)
ReadAFM ($file, &$map)
MakeFontDescriptor ($fm, $symbolic)
MakeWidthArray ($fm)
MakeFontEncoding ($map)
SaveToFile ($file, $s, $mode)
ReadShort ($f)
ReadLong ($f)
CheckTTF ($file)
MakeFont ($fontfile, $afmfile, $enc='cp1252', $patch=array(), $type='TrueType')
Function Documentation
CheckTTF()
CheckTTF ($file)
Definition at line 253 of file makefont.php.
References $file, ReadLong(), and ReadShort().
Referenced by MakeFont().
MakeFont()
MakeFont ($fontfile, $afmfile, $enc = 'cp1252', $patch = array(), $type = 'TrueType')
Definition at line 300 of file makefont.php.
References $diff, $enc, $file, AlchimieBAJ\main\ajax\$type, CheckTTF(), MakeFontDescriptor(), MakeFontEncoding(), MakeWidthArray(), ReadAFM(), ReadMap(), and SaveToFile().
MakeFontDescriptor()
MakeFontDescriptor ($fm, $symbolic)
Definition at line 137 of file makefont.php.
References $desc.
Referenced by MakeFont().
MakeFontEncoding()
MakeFontEncoding ($map)
Definition at line 213 of file makefont.php.
References ReadMap().
Referenced by MakeFont().
MakeWidthArray()
MakeWidthArray ($fm)
Definition at line 188 of file makefont.php.
References $cw.
Referenced by MakeFont().
ReadAFM()
ReadAFM ($file, & $map)
Definition at line 36 of file makefont.php.
References $file, and AlchimieBAJ\main\ajax\$param.
Referenced by MakeFont().
ReadLong()
ReadLong ($f)
Definition at line 247 of file makefont.php.
Referenced by CheckTTF().
ReadMap()
ReadMap ($enc)
Definition at line 10 of file makefont.php.
References $enc, and $file.
Referenced by MakeFont(), and MakeFontEncoding().
ReadShort()
ReadShort ($f)
Definition at line 241 of file makefont.php.
Referenced by CheckTTF().
SaveToFile()
SaveToFile ($file, $s, $mode)
Definition at line 232 of file makefont.php.
References $file.
Referenced by MakeFont().