Site local Alchimie: AlchimieBAJ\main\ajax Namespace Reference
AlchimieBAJ\main\ajax Namespace Reference
Functions
generateCSV ($data, $filename)
GetStats ($annee)
Variables
if (!isset($_SERVER[ 'HTTP_X_REQUESTED_WITH'])||strtolower($_SERVER[ 'HTTP_X_REQUESTED_WITH']) !='xmlhttprequest')
if(is_null($pdo)) if(isset($_POST['id'])) else
if (! isset($_SERVER[ 'HTTP_X_REQUESTED_WITH']) and strtolower($_SERVER[ 'HTTP_X_REQUESTED_WITH']) !='xmlhttprequest')
if(is_null($pdo)) try
if (! isset($_SERVER[ 'HTTP_X_REQUESTED_WITH']) and strtolower($_SERVER[ 'HTTP_X_REQUESTED_WITH']) !='xmlhttprequest')
$data = $statement->fetchAll(PDO::FETCH_ASSOC)
if(is_null($pdo)) $term = trim(strip_tags($_GET['term']))
$exact = trim(strip_tags($_GET['exact']))
else $newParameter = '%' . $term . '%'
$totalData = 0
$a_json = array()
$a_json_row = array()
while ($jeu=$statement->fetch())
$statement = null
$pdo = null
if (!isset($_SERVER[ 'HTTP_X_REQUESTED_WITH'])||strtolower($_SERVER[ 'HTTP_X_REQUESTED_WITH']) !='xmlhttprequest')
if(is_null($pdo)) $sqlConditions = array()
$sqlParameters = array()
if(isset($_POST['idVendeur'])) if(isset($_POST['idStatut'])) if(isset($_POST['vigilance'])) if(isset($_POST['code_barre'])) if(isset($_POST['nom_jeu'])) $sqlConditions [] = $SQL_5_6_whereAnnee
$sqlQuery = $SQL_5_getlistejeux . implode(' AND ', $sqlConditions) . $SQL_5_7_orderBy
while($jeu=$statement->fetch()) $json_data
if(!isset($_SERVER['HTTP_X_REQUESTED_WITH'])||strtolower($_SERVER['HTTP_X_REQUESTED_WITH']) !=='xmlhttprequest') $response
$res = $statement->fetch()
$response ['message1']
$response ['message2'] = '1'
catch (PDOException $e)
$stmt = $pdo->query($sql)
$csvFilename = "stats_bourse.csv"
$annee = $_POST["annee"]
if(is_null($pdo)) $idAcheteur = filter_var($_POST["idAcheteur"], FILTER_SANITIZE_STRING, FILTER_FLAG_STRIP_LOW | FILTER_FLAG_STRIP_HIGH)
$emailAcheteur = filter_var($_POST["emailAcheteur"], FILTER_SANITIZE_STRING, FILTER_FLAG_STRIP_LOW | FILTER_FLAG_STRIP_HIGH)
$nomAcheteur = filter_var($_POST["nomAcheteur"], FILTER_SANITIZE_STRING, FILTER_FLAG_STRIP_LOW | FILTER_FLAG_STRIP_HIGH)
$prenomAcheteur = filter_var($_POST["prenomAcheteur"], FILTER_SANITIZE_STRING, FILTER_FLAG_STRIP_LOW | FILTER_FLAG_STRIP_HIGH)
$adresseAcheteur = filter_var($_POST["adresseAcheteur"], FILTER_SANITIZE_STRING, FILTER_FLAG_STRIP_LOW | FILTER_FLAG_STRIP_HIGH)
$codePostalAcheteur = filter_var($_POST["codePostalAcheteur"], FILTER_SANITIZE_STRING, FILTER_FLAG_STRIP_LOW | FILTER_FLAG_STRIP_HIGH)
$villeAcheteur = filter_var($_POST["villeAcheteur"], FILTER_SANITIZE_STRING, FILTER_FLAG_STRIP_LOW | FILTER_FLAG_STRIP_HIGH)
$idTransaction = filter_var($_POST["idTransaction"], FILTER_SANITIZE_STRING, FILTER_FLAG_STRIP_LOW | FILTER_FLAG_STRIP_HIGH)
$sql = $SQL_41_attribution_acheteur_transaction
if(! isset($_SERVER['HTTP_X_REQUESTED_WITH']) and strtolower($_SERVER['HTTP_X_REQUESTED_WITH']) !='xmlhttprequest') $type =$_POST["type"]
$ret = AfficherTrans($type)
$SQL
if ($_SERVER["REQUEST_METHOD"]=="POST")
if (! isset($_SERVER[ 'HTTP_X_REQUESTED_WITH'])||strtolower($_SERVER[ 'HTTP_X_REQUESTED_WITH']) !='xmlhttprequest')
if(is_null($pdo)) $rsql =$SQL_31_getacheteur
$param = array()
$acheteurs = $statement->fetchAll(PDO::FETCH_ASSOC)
catch(PDOException $e) $recordsTotal = 0
Function Documentation
generateCSV()
AlchimieBAJ\main\ajax\generateCSV ($data, $filename)
Génère un fichier CSV à partir des données récupérées de la base de données.
Parameters
array $data Les données à convertir en CSV.
string $filename Le nom du fichier CSV à générer.
Definition at line 23 of file stats-finfestival-get.php.
References AlchimieBAJ\main\ajax\$data, and $file.
GetStats()
AlchimieBAJ\main\ajax\GetStats ($annee)
Cette fonction permet de récupérer l'ensembles des informations nécessaires à la page des stats.
$jeux va stocker le résultat de la requête tirée de al_bourse_liste $vente va stocker le résultat de la requête tirée de v_bourse_transactions $remb va stocker le résultat de la requête tirée de al_bourse_remboursements $dons va stocker le résultat de la requête tirée de al_bourse_dons
Parameters
{Integer} $annee
sur 4 chiffres
Returns
{Array} $a_json - Encodé en Json, contient : {Integer} $a_json['nbJeuxEnregistres'] {Integer} $a_json['nbJeuxStock'] {Integer} $a_json['nbJeuxVendus'] {Integer} $a_json['nbJeuxDonnés'] {Integer} $a_json['VentesCB'] {Integer} $a_json['VentesEspeces'] {Integer} $a_json['VentesCheque'] {Integer} $a_json['VentesSac'] - Nombre de sacs vendus {Integer} $a_json['totalStockPrixVendu'] - Valorisation du stock {Integer} $a_json['RembEspeces'] {Integer} $a_json['RembCheques'] {Integer} $a_json['RembPaypal'] {Integer} $a_json['totalRemb'] - Total déjà remboursé {Integer} $a_json['totalARendre'] - Somme prix rendu des jeux vendus {Integer} $a_json['totalDons']
Definition at line 48 of file stats-get.php.
References AlchimieBAJ\main\ajax\$a_json, AlchimieBAJ\main\ajax\$annee, AlchimieBAJ\main\ajax\$pdo, AlchimieBAJ\main\$SQL_26_getInfosJeux, AlchimieBAJ\main\$SQL_27_getInfosVentes, AlchimieBAJ\main\$SQL_28_getInfosRemb, AlchimieBAJ\main\$SQL_29_getInfosDons, and AlchimieBAJ\main\ajax\$statement.
Variable Documentation
$a_json
AlchimieBAJ::main::ajax\$a_json = array()
Script de traitement des fichiers CSV pour insertion dans les tables al_bourse_users et al_bourse_liste.
Definition at line 29 of file jeux-get.php.
Referenced by AlchimieBAJ\main\ajax\GetStats().
$a_json_row
AlchimieBAJ::main::ajax\$a_json_row = array()
Definition at line 30 of file jeux-get.php.
$acheteurs
AlchimieBAJ::main::ajax\$acheteurs = $statement->fetchAll(PDO::FETCH_ASSOC)
Definition at line 34 of file user-get-autocomplete.php.
$adresseAcheteur
AlchimieBAJ::main::ajax\$adresseAcheteur = filter_var($_POST["adresseAcheteur"], FILTER_SANITIZE_STRING, FILTER_FLAG_STRIP_LOW | FILTER_FLAG_STRIP_HIGH)
Definition at line 16 of file transaction-update.php.
$annee
AlchimieBAJ::main::ajax\$annee = $_POST["annee"]
Ce document fait l'ensemble des accès en base pour alimenter la page de stats.
C'est un ajax, appelé par la fonction js
See also
updateStats().
Definition at line 10 of file stats-get.php.
Referenced by AlchimieBAJ\main\AfficherDons(), AlchimieBAJ\main\AfficherRemb(), AlchimieBAJ\main\AfficherTrans(), and AlchimieBAJ\main\ajax\GetStats().
$codePostalAcheteur
AlchimieBAJ::main::ajax\$codePostalAcheteur = filter_var($_POST["codePostalAcheteur"], FILTER_SANITIZE_STRING, FILTER_FLAG_STRIP_LOW | FILTER_FLAG_STRIP_HIGH)
Definition at line 17 of file transaction-update.php.
$csvFilename
AlchimieBAJ::main::ajax\$csvFilename = "stats_bourse.csv"
Definition at line 49 of file stats-finfestival-get.php.
$data
AlchimieBAJ::main::ajax\$data = $statement->fetchAll(PDO::FETCH_ASSOC)
Definition at line 25 of file get-ventes.php.
Referenced by FPDF\_parsegif(), FPDF\_parsejpg(), FPDF\_parsepngstream(), FPDF\_putstream(), FPDF\_putstreamobject(), AlchimieBAJ\main\csvFromArray(), and AlchimieBAJ\main\ajax\generateCSV().
$emailAcheteur
AlchimieBAJ::main::ajax\$emailAcheteur = filter_var($_POST["emailAcheteur"], FILTER_SANITIZE_STRING, FILTER_FLAG_STRIP_LOW | FILTER_FLAG_STRIP_HIGH)
Definition at line 13 of file transaction-update.php.
$exact
AlchimieBAJ::main::ajax\$exact = trim(strip_tags($_GET['exact']))
Definition at line 12 of file jeux-get.php.
$idAcheteur
if (is_null($pdo)) AlchimieBAJ::main::ajax\$idAcheteur = filter_var($_POST["idAcheteur"], FILTER_SANITIZE_STRING, FILTER_FLAG_STRIP_LOW | FILTER_FLAG_STRIP_HIGH)
Definition at line 12 of file transaction-update.php.
$idTransaction
AlchimieBAJ::main::ajax\$idTransaction = filter_var($_POST["idTransaction"], FILTER_SANITIZE_STRING, FILTER_FLAG_STRIP_LOW | FILTER_FLAG_STRIP_HIGH)
Definition at line 19 of file transaction-update.php.
$json_data
while ($vendeur=$statement->fetch()) AlchimieBAJ::main::ajax\$json_data
Initial value:
= array(
    "recordsTotal" => intval($totalData),
    "recordsFiltered" => intval($totalData),
    "data" => $data
)
Definition at line 82 of file jeuxliste-getenstockspeed.php.
$newParameter
else AlchimieBAJ::main::ajax\$newParameter = '%' . $term . '%'
Definition at line 24 of file jeux-get.php.
$nomAcheteur
AlchimieBAJ::main::ajax\$nomAcheteur = filter_var($_POST["nomAcheteur"], FILTER_SANITIZE_STRING, FILTER_FLAG_STRIP_LOW | FILTER_FLAG_STRIP_HIGH)
Definition at line 14 of file transaction-update.php.
$param
AlchimieBAJ::main::ajax\$param = array()
Definition at line 17 of file user-get-autocomplete.php.
Referenced by FPDF\_httpencode(), and ReadAFM().
$pdo
AlchimieBAJ::main::ajax\$pdo = null
Definition at line 48 of file jeux-get.php.
Referenced by AlchimieBAJ\main\ajax\GetStats().
$prenomAcheteur
AlchimieBAJ::main::ajax\$prenomAcheteur = filter_var($_POST["prenomAcheteur"], FILTER_SANITIZE_STRING, FILTER_FLAG_STRIP_LOW | FILTER_FLAG_STRIP_HIGH)
Definition at line 15 of file transaction-update.php.
$recordsTotal
catch (PDOException $e) AlchimieBAJ::main::ajax\$recordsTotal = 0
Definition at line 26 of file vendeurs-get.php.
$res
AlchimieBAJ::main::ajax\$res = $statement->fetch()
Definition at line 24 of file sac-get.php.
Referenced by FPDF\_readstream(), FPDF\_UTF8encode(), FPDF\_UTF8toUTF16(), and AlchimieBAJ\main\pdf\GenererFacture().
$response [1/3]
if (!isset($_SERVER[ 'HTTP_X_REQUESTED_WITH'])||strtolower($_SERVER[ 'HTTP_X_REQUESTED_WITH']) !=='xmlhttprequest') AlchimieBAJ::main::ajax\$response
Initial value:
= array(
    'message1' => array(),
    'message2' => '0'
)
Definition at line 16 of file sac-get.php.
$response [2/3]
AlchimieBAJ::main::ajax\$response[ 'message1']
Initial value:
= array(
        'SAC_ID' => $res['id'],
        'SAC_JEU' => $res['nom_jeu'],
        'SAC_PRIX' => $res['vendu'],
        'SAC_CODEBARRE' => $res['code_barre']
    )
Definition at line 26 of file sac-get.php.
$response [3/3]
AlchimieBAJ::main::ajax\$response[ 'message2'] = '1'
Definition at line 34 of file sac-get.php.
$ret
AlchimieBAJ::main::ajax\$ret = AfficherTrans($type)
Definition at line 12 of file transactionliste-get.php.
Referenced by AlchimieBAJ\main\AfficherDons(), AlchimieBAJ\main\AfficherRemb(), AlchimieBAJ\main\AfficherTrans(), and AlchimieBAJ\main\getUser().
$rsql
if (is_null($pdo)) AlchimieBAJ::main::ajax\$rsql =$SQL_31_getacheteur
Definition at line 16 of file user-get-autocomplete.php.
$sql
AlchimieBAJ::main::ajax\$sql = $SQL_41_attribution_acheteur_transaction
Definition at line 74 of file transaction-update.php.
$SQL
AlchimieBAJ::main::ajax\$SQL
Initial value:
= "TRUNCATE al_bourse_users;
        TRUNCATE al_bourse_acheteur;
        UPDATE `al_bourse_liste` SET `id_utilisateur`=0 WHERE 1;
        UPDATE `al_bourse_liste` SET `id_utilisateur`=1, annee=".DATE('Y')." WHERE id=-1;"
Definition at line 15 of file upload_files.php.
$sqlConditions [1/2]
if (is_null($pdo)) AlchimieBAJ::main::ajax\$sqlConditions = array()
Definition at line 18 of file jeuxliste-getenstockspeed.php.
$sqlConditions [2/2]
if (isset($_POST[ 'idVendeur'])) if (isset($_POST[ 'idStatut'])) if (isset($_POST[ 'vigilance'])) if (isset($_POST[ 'code_barre'])) if (isset($_POST[ 'nom_jeu'])) AlchimieBAJ::main::ajax\$sqlConditions[] = $SQL_5_6_whereAnnee
Definition at line 47 of file jeuxliste-getenstockspeed.php.
$sqlParameters
AlchimieBAJ::main::ajax\$sqlParameters = array()
Definition at line 19 of file jeuxliste-getenstockspeed.php.
$sqlQuery
AlchimieBAJ::main::ajax\$sqlQuery = $SQL_5_getlistejeux . implode(' AND ', $sqlConditions) . $SQL_5_7_orderBy
Definition at line 50 of file jeuxliste-getenstockspeed.php.
$statement
AlchimieBAJ::main::ajax\$statement = null
Definition at line 47 of file jeux-get.php.
Referenced by AlchimieBAJ\main\AfficherDons(), AlchimieBAJ\main\AfficherRemb(), AlchimieBAJ\main\AfficherTrans(), AlchimieBAJ\main\pdf\GenererFacture(), AlchimieBAJ\main\pdf\GenererJustificatif(), AlchimieBAJ\main\ajax\GetStats(), and AlchimieBAJ\main\getUser().
$stmt
AlchimieBAJ::main::ajax\$stmt = $pdo->query($sql)
Definition at line 14 of file stats-finfestival-get.php.
$term
if (is_null($pdo)) AlchimieBAJ::main::ajax\$term = trim(strip_tags($_GET['term']))
Definition at line 11 of file jeux-get.php.
$totalData
AlchimieBAJ::main::ajax\$totalData = 0
Definition at line 28 of file jeux-get.php.
Referenced by AlchimieBAJ\main\getUser().
$type
if (! isset($_SERVER[ 'HTTP_X_REQUESTED_WITH']) and strtolower($_SERVER[ 'HTTP_X_REQUESTED_WITH']) !='xmlhttprequest') AlchimieBAJ::main::ajax\$type =$_POST["type"]
Definition at line 11 of file transactionliste-get.php.
Referenced by FPDF\_parsepngstream(), FPDF\_putfonts(), AlchimieBAJ\main\AfficherTrans(), FPDF\Image(), and MakeFont().
$villeAcheteur
AlchimieBAJ::main::ajax\$villeAcheteur = filter_var($_POST["villeAcheteur"], FILTER_SANITIZE_STRING, FILTER_FLAG_STRIP_LOW | FILTER_FLAG_STRIP_HIGH)
Definition at line 18 of file transaction-update.php.
catch
AlchimieBAJ::main::ajax\catch(PDOException $e) (PDOException $e)
Definition at line 35 of file sac-get.php.
else
if ($idAcheteur==0) AlchimieBAJ::main::ajax\else
Initial value:
{
    echo json_encode(['error' => 'ID de l\'acheteur manquant'])
Definition at line 30 of file acheteur-get.php.
if [1/6]
AlchimieBAJ::main::ajax\if($_SERVER["REQUEST_METHOD"]=="POST") ($_SERVER["REQUEST_METHOD"] = = "POST")
Definition at line 24 of file upload_files.php.
if [2/6]
AlchimieBAJ::main::ajax\if(! isset($_SERVER['HTTP_X_REQUESTED_WITH']) and strtolower($_SERVER['HTTP_X_REQUESTED_WITH']) !='xmlhttprequest') (! isset($_SERVER['HTTP_X_REQUESTED_WITH']) and strtolower($_SERVER['HTTP_X_REQUESTED_WITH']) ! = 'xmlhttprequest')
Ce fichier contient l'accès en base pour récupérer la somme en caisse.
Definition at line 10 of file argentencaisse-get.php.
if [3/6]
AlchimieBAJ::main::ajax\if(! isset($_SERVER['HTTP_X_REQUESTED_WITH']) and strtolower($_SERVER['HTTP_X_REQUESTED_WITH']) !='xmlhttprequest') (! isset($_SERVER['HTTP_X_REQUESTED_WITH']) and strtolower($_SERVER['HTTP_X_REQUESTED_WITH']) ! = 'xmlhttprequest')
Definition at line 6 of file get-ventes.php.
if [4/6]
AlchimieBAJ::main::ajax\if(! isset($_SERVER['HTTP_X_REQUESTED_WITH'])||strtolower($_SERVER['HTTP_X_REQUESTED_WITH']) !='xmlhttprequest') (! isset($_SERVER['HTTP_X_REQUESTED_WITH'])||strtolower($_SERVER['HTTP_X_REQUESTED_WITH']) ! = 'xmlhttprequest')
Definition at line 6 of file user-get-autocomplete.php.
if [5/6]
AlchimieBAJ::main::ajax::if (!isset($_SERVER['HTTP_X_REQUESTED_WITH'])||strtolower($_SERVER['HTTP_X_REQUESTED_WITH']) ! = 'xmlhttprequest')
Initial value:
{
    $statement = $pdo->prepare($SQL_25_getlistevente)
Definition at line 6 of file acheteur-get.php.
if [6/6]
AlchimieBAJ::main::ajax\if(!isset($_SERVER['HTTP_X_REQUESTED_WITH'])||strtolower($_SERVER['HTTP_X_REQUESTED_WITH']) !='xmlhttprequest') (!isset($_SERVER['HTTP_X_REQUESTED_WITH'])||strtolower($_SERVER['HTTP_X_REQUESTED_WITH']) ! = 'xmlhttprequest')
Definition at line 7 of file jeuxliste-getenstockspeed.php.
try
if (! isset($_SERVER[ 'HTTP_X_REQUESTED_WITH']) and strtolower($_SERVER[ 'HTTP_X_REQUESTED_WITH']) !='xmlhttprequest') if (is_null($pdo)) AlchimieBAJ::main::ajax\try
Initial value:
{
    $statement = $pdo->prepare($SQL_8_argentencaisse_get)
Definition at line 17 of file argentencaisse-get.php.
while
AlchimieBAJ::main::ajax::while ($jeu = $statement->fetch())
Initial value:
= array(
    "recordsTotal" => intval($totalData),
    "recordsFiltered" => intval($totalData),
    "data" => $data
)
Definition at line 31 of file jeux-get.php.